// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Booking struct {
	ID         uuid.UUID     `json:"id"`
	UserID     uuid.UUID     `json:"user_id"`
	TourID     uuid.UUID     `json:"tour_id"`
	PorterID   uuid.NullUUID `json:"porter_id"`
	Status     string        `json:"status"`
	Quantity   int32         `json:"quantity"`
	TotalPrice int64         `json:"total_price"`
	ExpiredAt  time.Time     `json:"expired_at"`
	CreatedAt  time.Time     `json:"created_at"`
	UpdatedAt  time.Time     `json:"updated_at"`
}
