// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Booking struct {
	ID         uuid.UUID     `json:"id"`
	UserID     uuid.UUID     `json:"user_id"`
	TourID     uuid.UUID     `json:"tour_id"`
	PorterID   uuid.NullUUID `json:"porter_id"`
	Quantity   int32         `json:"quantity"`
	TotalPrice sql.NullInt64 `json:"total_price"`
	CreatedAt  time.Time     `json:"created_at"`
	UpdatedAt  time.Time     `json:"updated_at"`
}
