// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateBooking(ctx context.Context, arg *CreateBookingParams) (*Booking, error)
	DeleteBooking(ctx context.Context, id uuid.UUID) error
	GetBookingByID(ctx context.Context, id uuid.UUID) (*Booking, error)
	GetBookingForUpdate(ctx context.Context, id uuid.UUID) (*Booking, error)
	ListHostBookings(ctx context.Context, arg *ListHostBookingsParams) ([]*Booking, error)
	ListUserBookings(ctx context.Context, arg *ListUserBookingsParams) ([]*Booking, error)
	UpdateBooking(ctx context.Context, arg *UpdateBookingParams) error
}

var _ Querier = (*Queries)(nil)
