openapi: 3.0.3
info:
  title: Auth API
  version: 1.0.0
  description: API cho xác thực người dùng
paths:
  /auth/register:
    post:
      summary: Đăng ký người dùng
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequestDto'
      responses:
        '200':
          description: Đăng ký thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'

  /auth/login:
    post:
      summary: Đăng nhập người dùng
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequestDto'
      responses:
        '200':
          description: Đăng nhập thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'

  /auth/otp:
    post:
      summary: Xác minh OTP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                otp:
                  type: string
              required: [email, otp]
      responses:
        '200':
          description: Xác minh thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'

  /auth/resend-otp:
    post:
      summary: Gửi lại OTP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required: [email]
      responses:
        '200':
          description: Gửi lại OTP thành công

  /auth/test:
    post:
      summary: Kiểm tra xác thực
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateRequestDto'
      responses:
        '200':
          description: Xác thực thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidateResponse'

components:
  schemas:
    RegisterRequestDto:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        confirmPassword:
          type: string
      required: [email, password, confirmPassword]

    RegisterResponse:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        data:
          type: object
          nullable: true

    LoginRequestDto:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required: [email, password]

    LoginResponse:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string

    ValidateRequestDto:
      type: object
      properties:
        token:
          type: string
      required: [token]

    ValidateResponse:
      type: object
      properties:
        isValid:
          type: boolean
        userId:
          type: string
