version: "3.3"

services:
  postgres:
    container_name: app_postgres
    image: postgres
    networks:
      - app
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    container_name: app_redis
    image: redis
    networks:
      - app
    volumes:
      - ./redis-data:/data
    restart: unless-stopped

networks:
  app: