// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.20.3
// source: user.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Empty } from "./google/protobuf/empty";

export const protobufPackage = "user";

export interface Role {
  id: string;
  name: string;
}

export interface User {
  id: string;
  email: string;
  fullname: string;
  dob: string;
  address: string;
  phoneNumber: string;
  role: Role;
  permissions: string[];
}

export interface CreateRequest {
  email: string;
  fullname: string;
  password: string;
  roleName: string;
}

export interface GetByIdRequest {
  id: string;
}

export interface GetByIdResponse {
  user: User | undefined;
}

export interface CheckExistByEmailRequest {
  email: string;
}

export interface CheckExistByEmailResponse {
  result: boolean;
}

export interface CheckLoginRequest {
  email: string;
  password: string;
}

export interface CheckLoginResponse {
  user: User | undefined;
}

export const USER_PACKAGE_NAME = "user";

export interface UserServiceClient {
  create(request: CreateRequest): Observable<Empty>;

  getById(request: GetByIdRequest): Observable<GetByIdResponse>;

  checkExistByEmail(request: CheckExistByEmailRequest): Observable<CheckExistByEmailResponse>;

  checkLogin(request: CheckLoginRequest): Observable<CheckLoginResponse>;
}

export interface UserServiceController {
  create(request: CreateRequest): void;

  getById(request: GetByIdRequest): Promise<GetByIdResponse> | Observable<GetByIdResponse> | GetByIdResponse;

  checkExistByEmail(
    request: CheckExistByEmailRequest,
  ): Promise<CheckExistByEmailResponse> | Observable<CheckExistByEmailResponse> | CheckExistByEmailResponse;

  checkLogin(
    request: CheckLoginRequest,
  ): Promise<CheckLoginResponse> | Observable<CheckLoginResponse> | CheckLoginResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["create", "getById", "checkExistByEmail", "checkLogin"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
