definitions:
  entity.Booking:
    type: object
info:
  contact: {}
paths:
  /bookings:
    post:
      consumes:
      - application/json
      description: Gửi yêu cầu đặt tour
      parameters:
      - description: Thông tin booking
        in: body
        name: booking
        required: true
        schema:
          $ref: '#/definitions/entity.Booking'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/entity.Booking'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Tạo booking mới
      tags:
      - Booking
  /bookings/{id}:
    get:
      consumes:
      - application/json
      description: Truy vấn chi tiết booking theo ID
      parameters:
      - description: Booking ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Booking'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Lấy thông tin booking
      tags:
      - Booking
  /bookings/{id}/cancel:
    post:
      consumes:
      - application/json
      description: Hủy booking theo ID
      parameters:
      - description: Booking ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Booking'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Hủy booking
      tags:
      - Booking
swagger: "2.0"
