definitions:
  entity.Booking:
    properties:
      created_at:
        example: "2025-05-11T15:04:05Z"
        type: string
      expired_at:
        example: "2025-06-30T15:04:05Z"
        type: string
      id:
        example: 123e4567-e89b-12d3-a456-426614174000
        type: string
      porter_id:
        example: 123e4567-e89b-12d3-a456-426614174003
        type: string
      quantity:
        example: 3
        type: integer
      status:
        allOf:
        - $ref: '#/definitions/entity.BookingStatus'
        example: PENDING
      total_price:
        example: 1500000
        type: integer
      tour_id:
        example: 123e4567-e89b-12d3-a456-426614174002
        type: string
      updated_at:
        example: "2025-05-12T10:00:00Z"
        type: string
      user_id:
        example: 123e4567-e89b-12d3-a456-426614174001
        type: string
    type: object
  entity.BookingStatus:
    enum:
    - EXPIRED
    - PENDING
    - CANCEL
    - SUCCESS
    type: string
    x-enum-varnames:
    - BookingStatusExpired
    - BookingStatusPending
    - BookingStatusCancel
    - BookingStatusSuccess
info:
  contact: {}
paths:
  /api/v1/booking/{id}:
    get:
      consumes:
      - application/json
      description: Truy vấn chi tiết booking theo ID
      parameters:
      - description: Booking ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Booking'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Lấy thông tin booking
      tags:
      - Booking
  /api/v1/booking/{id}/cancel:
    post:
      consumes:
      - application/json
      description: Hủy booking theo ID
      parameters:
      - description: Booking ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Booking'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Hủy booking
      tags:
      - Booking
  /api/v1/booking/create:
    post:
      consumes:
      - application/json
      description: Gửi yêu cầu đặt tour
      parameters:
      - description: Thông tin booking
        in: body
        name: booking
        required: true
        schema:
          $ref: '#/definitions/entity.Booking'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/entity.Booking'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Tạo booking mới
      tags:
      - Booking
  /api/v1/booking/ping-notification:
    get:
      consumes:
      - application/json
      description: Send a ping message to notification service via Redis
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Ping notification service
      tags:
      - Notification
swagger: "2.0"
