// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateNotification(ctx context.Context, arg *CreateNotificationParams) (*Notification, error)
	DeleteNotification(ctx context.Context, id uuid.UUID) error
	GetNotificationByID(ctx context.Context, id uuid.UUID) (*Notification, error)
	ListNotificationsByUser(ctx context.Context, userID uuid.UUID) ([]*Notification, error)
	MarkNotificationsAsRead(ctx context.Context, dollar_1 []uuid.UUID) error
	ReadNotification(ctx context.Context, id uuid.UUID) error
	UpdateNotification(ctx context.Context, arg *UpdateNotificationParams) (*Notification, error)
}

var _ Querier = (*Queries)(nil)
