// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Tour struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Host        uuid.UUID      `json:"host"`
	Slot        int32          `json:"slot"`
	Status      string         `json:"status"`
	StartAt     sql.NullTime   `json:"start_at"`
	EndAt       sql.NullTime   `json:"end_at"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}
