// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Tour struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	HostID        uuid.UUID `json:"host_id"`
	Price         int32     `json:"price"`
	Level         string    `json:"level"`
	Distance      int32     `json:"distance"`
	Elevation     int32     `json:"elevation"`
	Duration      string    `json:"duration"`
	Location      string    `json:"location"`
	Images        string    `json:"images"`
	Rate          string    `json:"rate"`
	Slot          int32     `json:"slot"`
	AvailableSlot int32     `json:"available_slot"`
	Status        string    `json:"status"`
	StartAt       time.Time `json:"start_at"`
	EndAt         time.Time `json:"end_at"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}
