// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateTour(ctx context.Context, arg *CreateTourParams) (*Tour, error)
	DeleteTour(ctx context.Context, id uuid.UUID) error
	GetTourByHostId(ctx context.Context, hostID uuid.UUID) ([]*Tour, error)
	GetTourByID(ctx context.Context, id uuid.UUID) (*Tour, error)
	ListTours(ctx context.Context, arg *ListToursParams) ([]*Tour, error)
	UpdateAvailableSlot(ctx context.Context, arg *UpdateAvailableSlotParams) (*Tour, error)
	UpdateTour(ctx context.Context, arg *UpdateTourParams) error
}

var _ Querier = (*Queries)(nil)
