CREATE TABLE "tour" (
                    "id" uuid PRIMARY KEY,
                    "name" varchar NOT NULL,
                    "description" text NOT NULL,
                    "host_id" uuid NOT NULL,
                    "price" int NOT NULL,
                    "level" varchar NOT NULL,
                    "distance" int NOT NULL,
                    "elevation" int NOT NULL,
                    "duration" varchar NOT NULL,
                    "location" varchar NOT NULL,
                    "images" varchar NOT NULL,
                    "rate" varchar NOT NULL,
                    "slot" int NOT NULL,
                    "available_slot" int NOT NULL,
                    "status" varchar NOT NULL,
                    "start_at" timestamptz NOT NULL,
                    "end_at" timestamptz NOT NULL,
                    "created_at" timestamptz NOT NULL DEFAULT (now()),
                    "updated_at" timestamptz NOT NULL DEFAULT (now())
);
